### ISSUE TITLE
Processing history

### ISSUE THREAD

**Issue by cneud** [altoxml/schema#39]
Recently, several feature requests were submitted that relate to the recording of processing information in ALTO (see #13, #27, #36, #35 for in-depth information). In an attempt to consolidate and harmonize the requests, this issue shall serve as the main point of discussion from now on.

Features requested:
- [x] Change _OCRProcessing_ to generic _Processing_ (#13, #35).
- [x] Change _preProcessingStep_, _ocrProcessingStep_, _postProcessingStep_ to generic _processingStep_ with _processingStepType_ element to record the type of processing performed (#13).
- [x] Add required attribute _ID_ to _ProcessingStepType_ (#13, #27, #35).
- [x] Add optional attributes _COR_ (CORRECTEDBY), _VER_ (VERIFIEDBY) for all elements. The attributes are holding a list of references (using the _ID_ attribute) to all _processingStepType_ entries which have changed the original value (#27).
- [x] Being able to link elements to a particular _processingStep_ (#35). 
  Example: Use Tesseract's page segmentation with Ocropus's recognition, so that _TextLine_ elements are sourced from one _ProcessingStep_ (Ocropus), but their text content from another one (Tesseract).
- [x] Common vocabulary of _processingStepType_ attribute values to increase interoperability (#36)

**Comment by jukervin** [comment]
Minimally common vocabulary is needed for processingStepType

**Comment by Jo-CCS** [comment]
For referencing the processing IDs on the elements I propose to add a list of IDs space separated as done in METS for the DMDID's.
		<xsd:attribute name="DMDID" type="xsd:IDREFS" use="optional"/>

Also I would like to recommend to have at least the description of processing node as mandatory. Also the datetime could be mandatory as it has quite important information what and when it was done.

**Comment by cneud** [comment]
**Minutes of the technical call 27-07-2016**

I. Change _OcrProcessing_ to _Processing_ and _preProcessingStep_, _ocrProcessingStep_, _postProcessingStep_ to generic _processingStep_ with _ProcessingStepType_ and required _ID_ attribute.
- Is there a need to explicitely define order/sequence of processing?
- Does _ProcessingDateTime_ define start or end of processing?
- Possibility to derive duration of processing?     

Instead of _ProcessingDateTime_, there should be _ProcessingStartDateTime_ and _ProcessingEndDateTime_ (mandatory). Duration can then be inferred if needed.

- How to represent sequence of _processingStep_?

Follow example of METS with space separated IDs - e.g. 
```xml
<TextLine ID="ID069" [...] PROCESSINGREFS="ID001 ID002 ID003 ID004 ID005">
```
II. Add optional attributes _COR_ (CORRECTEDBY), _VER_ (VERIFIEDBY) for all elements.
- Example newspaper digitisation: only headlines manually corrected
- Rather just change CS (correction status) attribute?
- This would result in mixing of metadata & content
- Difficulty of inheritance - can child elements inherit _processingStep_ from parent? For which use cases? E.g. Binarization (yes) vs. Rotation (no).

Further discussion and examples are required.

III. Common vocabulary for _processingStepType_
- E.g. PREMIS uses generic [eventType](http://id.loc.gov/vocabulary/preservation/eventType/collection_PREMIS) or METS [agent](https://www.loc.gov/standards/mets/docs/mets.v1-5.html#agent)
- Huge diversity of _processingStep_
- Few, very generic categories, e.g. relating to image/text/annotations(tags)?
- Need better understanding of use cases.

Look at other examples (interoperability). Keep it practical.

**Comment by jpmoreux** [comment]
Practical use cases I recently encountered:
- correction of rotation on images
- correction of curvature on images
- localized text correction (newspaper headlines)
- semantic annotation : named entities recognition, signature recognition (authors, illustrators)
- structure extraction : ALTO -> EPUB -> ALTO with some logical structure embedded

As I wrote in another comment, we should warn people to store these informations in the document manifest (METS, etc.), at the higher possible level, if the same processing is applied to all the ALTO files of a specific document. But some kind of processing are interesting to described locally (eg which text blocks have been corrected).

**Comment by cneud** [comment]
**Minutes of the technical call 30-03-2017**

- **omit** optional attributes COR (CORRECTEDBY), VER (VERIFIEDBY) and rather express this via _processingStepType_ vocabulary instead
- **introduce** renaming of _OcrProcessing_ to _Processing_ and _preProcessingStep_, _ocrProcessingStep_, _postProcessingStep_ to generic _processingStep_ with _ProcessingStepType_ and add required _ID_ attribute concurrently to current history tracking, which will be **declared deprecated**
- **add** common vocabulary comprising the types _ContentGeneration_, _ContentModification_, _PreOperation_, _PostOperation_, _Other_ and referencing a list of IDs as in [METS DMDID's](https://github.com/altoxml/schema/issues/39#issuecomment-235584104)
- @cneud to create a new draft schema with these changes before next board call

**Comment by acpopat** [comment]
Hi, I'm interested in participating in discussions on this topic.  I'm new to the topic of data provenance aside having used systems in the past that provided some form of it.

**Comment by cneud** [comment]
Initial draft for changes listed above: https://github.com/altoxml/schema/tree/master/v4

**Comment by cneud** [comment]
Possibly of interest for more sophisticated provenance/processing history tracking: 
https://www.w3.org/TR/prov-overview/

**Comment by acpopat** [comment]
Some processing histories may not be simple sequential pipelines and may require a more general graph structure. As mentioned in today's board call, some OCR post-correction schemes provide examples of such processing:

[merging results from multiple OCR engines](https://link.springer.com/chapter/10.1007/978-3-642-20227-8_1)

[post-correction using multiple information sources](http://www.frakturschrift.com/_media/en:gothicocr_furrer_volk_2011.pdf)

[coalescing information from multiple page images and their OCR results](http://ieeexplore.ieee.org/document/6195346/?reload=true)

If it is desired that the results of such processing be represented in ALTO, then a more general provenance scheme capable of representing graph-structured dependencies might be required, such as that referred to by Clemens in his Aug 2 comment.

**Comment by cneud** [comment]
Included in [v4.0](https://github.com/altoxml/documentation/wiki/v4.0-Changes).
